var array =[20,5,6,70,80,90,2,3,4,1,20];
console.log("******************ascending then descending********************");
sortMyArray(array);
console.log("======================================");
console.log("***************************************");
console.log("******************Filter********************");
FilterMyArray(array);
console.log("***************************************");
console.log("The Max value is  :",Math.max(...array)) ;
console.log("The min value is :",Math.min(...array));
console.log("****************Object Creator*********************");
CreateAnObject();